<?php
$faqlist = $this->getFaqlist();
?>

<div id="faq-list">
  <div class="page-title">
    <h1>Frequently Asked Questions</h1>
  </div>
  <?php if(!empty($faqlist)): ?>
  <div class="std">
    <ul class="disc">
      <?php foreach($faqlist as $faq): ?>
        <li><h4><a href="<?php echo Mage::getUrl('faq/index/view/', array('faq_id' => $faq['faq_id'])); ?>"><?php echo $this->escapeHtml($faq['title']); ?></a></h4></li>
      <?php endforeach; ?>
    </ul>
  </div>
  <?php else: ?>
    <p>There are no  available questions.</p>
  <?php endif; ?>
</div>
