

<div id="faq-list">
  <div class="page-title">
    <h1>Frequently Asked Questions</h1>
  </div>
  <?php if(!empty($this->getFaqlist())): ?>
  <div class="std">
    <ul class="disc">
      <?php foreach($this->getFaqlist() as $faq): ?>
        <li><h4><a href="index/view/faq_id/<?php echo $faq['faq_id']; ?>"><?php echo $faq['title']; ?></a></h4></li>
      <?php endforeach; ?>
    </ul>
  </div>
  <?php else: ?>
    <p>There are no  available questions.</p>
  <?php endif; ?>
</div>
